### PR TITLE
Refresh preview on fast refresh

### LINKED ISSUE #288: Preview is not working well when component changes.
**Description*
Preview is not working well when the component changes. 
I have a component which has title props. I changed the title props value but ui is not updated. After clicked open preview, UI is updated.

**Environment**
- RN IDE: v0.0.14
- EXPO: ~51.0.1 RN: 0.74.1

Video 
https://github.com/software-mansion/react-native-ide/assets/37181742/efb354e4-4295-4306-bc7b-b42c3fc9eca7

### PR DESCRIPTION
**Pull request by jakub-gonet**
Fast refresh is triggered when props are changed in previewed component. We didn't accommodate for that previously, as we only rendered preview once, after clicking a button from code lenses.

Additionally:
- cleared up logic in code lenses and added a check for preview import to prevent false positives.
- added check preventing crash on calling `preview()` without any component.
- fixed URL being out of sync when switching between preview/non-preview

Fixes #288.

### CODE REVIEW

File: packages/vscode-extension/lib/wrapper.js [hunk 1]
```diff
@@ -209,6 +216,10 @@ export function PreviewAppWrapper({ children, ...rest }) {
       };
       LoadingView.hide = () => {
         devtoolsAgent._bridge.send("RNIDE_fastRefreshComplete");
+        if (isRunningPreview()) {
+          // refresh preview component
+          openPreview(getCurrentSceneName());
```
Comment (kmagiera) [inline packages/vscode-extension/lib/wrapper.js:221]: I like all the other changes in this PR except for this one. It doesn't seem like the right choice to manually fix fast-refresh behavior. I wonder why does it in the main app but not in preview,  and would expect it to "just work" here as well? Maybe it's because preview is the root element and fast refresh doesn't support it? Maybe it'd be enough to just wrap it in some other root component?

File: packages/vscode-extension/src/webview/components/UrlBar.tsx [hunk 2]
```diff
@@ -57,7 +56,10 @@ function UrlBar({ project, disabled }: UrlBarProps) {
         <span className="codicon codicon-refresh" />
       </IconButton>
       <IconButton
-        onClick={() => project.goHome()}
+        onClick={() => {
+          project.goHome();
+          setUrlList([]);
```
Comment (jakub-gonet) [inline packages/vscode-extension/src/webview/components/UrlBar.tsx:61]: This isn't ideal but we relied on metro reload to do it for us. In the future, we need to keep `/` always in the URL list. I'll create a ticket for that.

File: packages/vscode-extension/lib/expo_router_plugin.js [hunk 3]
```diff
@@ -1,18 +1,21 @@
-import { useSyncExternalStore, useEffect } from "react";
-import { useRouter } from "expo-router";
 import { store } from "expo-router/build/global-state/router-store.js";
```
Comment (jakub-gonet) [inline packages/vscode-extension/lib/expo_router_plugin.js:1]: Moved the store import to the top so it's more evident that those two files are different only there.

File: packages/vscode-extension/lib/wrapper.js [hunk 4]
```diff
@@ -47,35 +51,34 @@ export function PreviewAppWrapper({ children, ...rest }) {
...
     },
-    [rootTag]
+    [rootTag, devtoolsAgent]
   );
 
   const closePreview = useCallback(() => {
-    const SceneTracker = require("react-native/Libraries/Utilities/SceneTracker");
-    const isRunningPreview = isPreviewUrl(SceneTracker.getActiveScene().name);
-    if (isRunningPreview) {
+    if (currentPreviewKey) {
```
Comment (kmagiera) [inline packages/vscode-extension/lib/wrapper.js:81]: maybe check active scene name, we don't need the exact preview name here as we only check if its running or not

**Review by kmagiera — CHANGES_REQUESTED** [review]
Added some comments inline. Also please remove changes to navigation integration interface. If there are issues in expo router integration due to early navChange calls, this should be handled by that implementation alone. Also such changes shouldn't be a part of this PR as they seem to be fixing a different problem

File: packages/vscode-extension/lib/preview.js [hunk 5]
```diff
@@ -1,36 +1,31 @@
...
+  return (
+    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
+      {previewData.component}
+    </View>
+  );
 }
 
 export function preview(component) {
-  if (component._source == null) {
+  if (!component || component._source === null) {
```
Comment (kmagiera) [inline packages/vscode-extension/lib/preview.js:20]: I think we may want to have `==` check here. I think `_source` could be `undefined` here too, and since it's internal field I wouldn't rely on it being set to `null`

**Review by kmagiera — APPROVED** [review]
Looks good, please check the inline comment I added tho
