### PR TITLE
Fix - display url params 

### LINKED ISSUE #443: URL Parameters don't display in the search
Currently, URL parameters don't display in the search panel
- Version of currently used React Native IDE 0.16.0

https://github.com/software-mansion/react-native-ide/assets/77052270/9f2b4b59-0b6d-4444-be48-ce927234eb49

### PR DESCRIPTION
**Pull request by kewinzaq1**
### Problem
Currently, URL parameters don't display in the search panel
Fixes #443 
https://github.com/software-mansion/react-native-ide/assets/77052270/fc3f2489-5e7d-46cd-865b-473aa54a0eaa

### How Has This Been Tested: 
Go to a page with parameters, and then you can see this problem, after this fix this issue no longer happens
https://github.com/software-mansion/react-native-ide/assets/77052270/f1c20113-86a1-4ea3-816c-9fc5fb7e4d4e

### CODE REVIEW

File: packages/vscode-extension/lib/wrapper.js [hunk 1]
```diff
@@ -82,9 +82,12 @@ export function PreviewAppWrapper({ children, initialProps, ..._rest }) {
 
   const handleNavigationChange = useCallback(
     (navigationDescriptor) => {
+      const queryParams = new URLSearchParams(navigationDescriptor.params).toString();
       navigationHistory.set(navigationDescriptor.id, navigationDescriptor);
       devtoolsAgent?._bridge.send("RNIDE_navigationChanged", {
-        displayName: navigationDescriptor.name,
+        displayName: `${navigationDescriptor.name}${
```
Comment (kmagiera) [inline packages/vscode-extension/lib/wrapper.js:88]: I'd much rather prefer for the name to already contain params for routes with parameters. We support expo router here only for the time being but the API is designed to be routing agnostic and for other solutions params may be formatted diferently.

The semantics of the "name" prop here is the "display name", so it is ok for the expo router plugin to format the params when appropriate

**Review by kmagiera — CHANGES_REQUESTED** [review]
Thanks for this. I pointed out in an inline comment that we'd want the expo router plugin to append params when passing "name" prop for the route. Would be happy to merge this when you made that change

File: packages/vscode-extension/lib/wrapper.js (hunk 1 above)
Comment (kewinzaq1) [reply packages/vscode-extension/lib/wrapper.js:88]: @kmagiera got it sounds reasonable

File: packages/vscode-extension/lib/expo_router_plugin.js [hunk 2]
```diff
@@ -17,9 +17,12 @@ function useRouterPluginMainHook({ onNavigationChange }) {
   const pathname = routeInfo?.pathname;
   const params = routeInfo?.params;
 
+  const displayParams = new URLSearchParams(params).toString();
```
Comment (kewinzaq1) [inline packages/vscode-extension/lib/expo_router_plugin.js:20]: info: copy pasted since as I know the v2 plugin will be removed and similar approach was recommended in previous implementation

**Review by kmagiera — APPROVED** [review]
This looks good, thank you!
